### ISSUE TITLE
Lesson 6 Abstractions I

### ISSUE THREAD

**Issue by emorchy** [jqueiroz/lojban.io#102]
After learning about {ni} and {du’u}, I have noticed other abstractions such as {za'i} or “state of”. After talking to a member in #ckule, it has come to my attention that {za’i} would be a better abstraction for *gleki* instead of {nu}. Part of the reason I (and many others) were confused was because of one example for each abstraction. If we had two examples for each abstraction, we could greatly expand on the flashcards and make abstractions much easier to understand. What do you think?

**Comment by jqueiroz** [comment]
Strongly agree, having two or more examples for each abstraction would help significantly!

Regarding "za'i" specifically, I would prefer to cover it in a future lesson. According to [CLL 11.3: Types of event abstractions](https://lojban.pw/cll/uncll-1.2.10/xhtml_section_chunks/section-event-types.html), "za'i" is a more specific type of "nu", so I think it makes sense to teach nu/du'u/sedu'u in Abstractions 1 and then cover the subtypes of nu in Abstractions N.

Perhaps you could add 3-4 examples for the subtypes mentioned in CLL 11.3 (point-event abstractor, process abstractor, activity abstractor and state abstractor) and hint that there exist separate words for each of those, but mention that they will be covered only in a later lesson?

I think this would make abstractions much easier to understand, as you mentioned, and would not place too much of a cognitive burden on the reader (no need to memorize all sub-event-abstractors initially).

**Comment by emorchy** [comment]
Okay. I will hint at subtype abstractions for a later lesson, and I will mention that more than one abstraction can be included in a sentence. I will most likely show an example of this. Thank you.

**Comment by jqueiroz** [comment]
Thank you!
