### ISSUE TITLE
A sort of typo in exercise: [courseId=grammar-intro_eng][lessonNumber=13][exerciseId=393]

### ISSUE THREAD

**Issue by vinivosh** [jqueiroz/lojban.io#114]
# Description
The word `you` appears twice in the sentence. I tried to correct this myself in the exercises but their generation seems way more complex than I could grasp by a quick read 😛 
I would guess the problem is the generator for the "sumtcita part" spat out a sentence ended with the word `you` and the generator for the rest of the sentence spat out one that started with `you`.

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=13][exerciseId=393]
- Exercise payload: {"sentences":[{"text":"Who made you you translate to Lojban?","lojbanic":false}],"title":"Translate this sentence","type":"typing"}
- Attempted solution: {"text":"gau ma do fanva fi lo lojbo"}
- Attempted solution was classified as correct: yes
- Validation payload: {"canonicalAnswer":"gau ma do fanva fi lo lojbo","correct":true}

**Comment by emorchy** [comment]
Thank you for submitting this issue. You are indeed correct, and I have submitted a pull request resolving this issue. Nice catch!

**Comment by jqueiroz** [comment]
Thank you @vinivosh and @emorchy!
