### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=1][exerciseId=4414]

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [jqueiroz/lojban.io#12]
# Description
If possible, please provide a brief description of what is wrong with this exercise.

One of the posible answers is blank, this makes it look broken.

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=1][exerciseId=4414]
- Exercise payload: {"alternatives":["","zdani","do"],"sentences":[{"text":"zdani do","lojbanic":true}],"title":"Identify the <b>selbri</b>","type":"single-choice"}
- Attempted solution: {"correctAlternative":"zdani"}
- Attempted solution was classified as correct: yes
- Validation payload: {"correct":true,"correctAlternative":"zdani"}

**Comment by jqueiroz** [comment]
Thank you!

These empty sumti alternatives were supposed to appear as "zo'e" instead of "", but I had forgotten to do that for the "Identity the selbri" exercises.
