### ISSUE TITLE
Incorrect exercise: [deckId=eng_contextualized-brivla][exerciseId=4347]

### ISSUE THREAD

**Issue by impression28** [jqueiroz/lojban.io#121]
# Description
I think the alternative "tntity" is a typo.

# Diagnostics information (do not remove)
- Exercise identifier: [deckId=eng_contextualized-brivla][exerciseId=4347]
- Exercise payload: {"alternatives":["facts","subject","tntity"],"sentences":[],"title":"Identify <b>lo se morji ku</b>","type":"single-choice"}
- Attempted solution: {"correctAlternative":"subject"}
- Attempted solution was classified as correct: no
- Validation payload: {"correct":false,"correctAlternative":"facts"}

**Comment by jqueiroz** [comment]
Fixed! Thanks for reporting!
