### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=13][exerciseId=1700]

### ISSUE THREAD

**Issue by Ushiofan4life** [jqueiroz/lojban.io#123]
# Description
I think the canonical answer is missing a "cu" or "ku" before "vecnu"?
vecnu ought to be the selbri, but it seems to be forming a tanru with lo ctuca.

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=13][exerciseId=1700]
- Exercise payload: {"sentences":[{"text":"Did the instructor sell the house that you found beautiful?","lojbanic":false}],"title":"Translate this sentence","type":"typing"}
- Attempted solution: {"text":"xu lo ctuca cu vecnu lo zdani poi do se melbi"}
- Attempted solution was classified as correct: no
- Validation payload: {"canonicalAnswer":"xu lo ctuca vecnu lo zdani poi melbi do","correct":false}

**Comment by Ushiofan4life** [comment]
Note that I don't necessarily think my attempted solution should be recognised as correct as "...poi melbi do" or "...poi do se melbi ke'a" would have been better than "...poi do se melbi".

**Comment by emorchy** [comment]
Thank you @Ushiofan4life for submitting this issue! I created pull request (#124) that fixes the exercise. Good luck with the rest of your learning, and please continue to provide feedback!

**Comment by jqueiroz** [comment]
Thank you @Ushiofan4life and @emorchy! :)
