### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=4][exerciseId=1541]

### ISSUE THREAD

**Issue by Aoriseth** [jqueiroz/lojban.io#129]
# Description
If possible, please provide a brief description of what is wrong with this exercise.

Since we are talking 'to' the beautiful person and not 'about' them, should the answer not be 
mi tavla **fi** lo melbi prenu ku
or
mi tavla **zo'e** lo melbi prenu ku
?

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=4][exerciseId=1541]
- Exercise payload: {"sentences":[{"text":"I talked to the beautiful person.","lojbanic":false}],"title":"Translate this sentence","type":"typing"}
- Attempted solution: {"text":"mi tavla fi lo melbi prenu ku"}
- Attempted solution was classified as correct: no
- Validation payload: {"canonicalAnswer":"mi tavla lo melbi prenu ku","correct":false}

**Comment by jqueiroz** [comment]
Thanks for reporting!

In tavla, the x2 corresponds to the person being talked to, and the x3 corresponds to the subject of the conversation. So "mi tavla lo melbi prenu ku" already means "I talked to the beautiful person".

This is a bit different from dunda, where the x2 is the gift and the x3 is the recipient, which might be the source of the confusion,

**Comment by Aoriseth** [comment]
My apologies, you are correct. I was incorrectly thinking about ta'asku instead of tavla.

**Comment by jqueiroz** [comment]
No problem, thanks for reporting! Happy learning :-)
