### ISSUE TITLE
(Possibly) Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=7][exerciseId=1342]

### ISSUE THREAD

**Issue by Alch-Emi** [jqueiroz/lojban.io#131]
# Description
It could be that I am just being dumb here, but I'm not sure I understand why this is wrong.

I would expect that

> dunda fi do fe lo gerku

would be equivalent to 

> dunda lo gerku do

in that both have the selbri `dunda` with sumti `x1 = zo'e`, `x2 = lo gerku ku`, `x3 = do`, with the first being specified using an implicit `zo'e`, `fi` to fill x3, and `fe` to fill x2, while the second fills x2 and x3 using the natural positions.

Is this just my misunderstanding of the language, or is there a mistake here? 

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=7][exerciseId=1342]
- Exercise payload: {"sentences":[{"text":"The person said that she would give you the dogs.","lojbanic":false}],"title":"Translate without using \"ku\"","type":"typing"}
- Attempted solution: {"text":"lo prunu cu cusku lo se du'u dunda fi do fe lo gerku"}
- Attempted solution was classified as correct: no
- Validation payload: {"canonicalAnswer":"lo prenu cu cusku lo se du'u dunda lo gerku do","correct":false}

**Comment by bowdie** [comment]
I think the issue could be that `prenu` has been spelt `prunu` in the attempted solution.

Otherwise your solution has the same meaning as the correct answer. @jqueiroz is there a way to get back to an exercise directly to test?

**Comment by Alch-Emi** [comment]
aa that's almost certainly it.  I'm sorry for the trouble

**Comment by jqueiroz** [comment]
Thank you @Alch-Emi for reporting and thank you @bowdie for looking into this :)

bowdie is correct, after changing prunu -> prenu both sentences canonicalize to the same value ("lo prenu ku cusku lo se du'u dunda lo gerku ku do kei ku"), so Alch-Emi's solution is accepted.

Sorry for the delay in getting to this.
