### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=27][exerciseId=1180]

### ISSUE THREAD

**Issue by asengelhart** [jqueiroz/lojban.io#132]
# Description
Previous lessons had clarified that `lerci` should refer only to events, and that stating that a person is late must be done via `x1 jai lerci` or `tu'a x1 cu lerci`. Thus, it appears that this answer should be `lo va prenu jai lerci` or `tu'a lo va prenu cu lerci`.

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=27][exerciseId=1180]
- Exercise payload: {"sentences":[{"text":"The moderately distant person is late.","lojbanic":false}],"title":"Translate this sentence","type":"typing"}
- Attempted solution: {"text":"lo va prenu jai lerci"}
- Attempted solution was classified as correct: no
- Validation payload: {"canonicalAnswer":"lo va prenu cu lerci","correct":false}

**Comment by jqueiroz** [comment]
Thank you, good catch! I fixed the incorrect translations.
