### ISSUE TITLE
(Possibly) Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=11][exerciseId=1718]

### ISSUE THREAD

**Issue by bowdie** [jqueiroz/lojban.io#134]
# Description
This could be my lack of understanding of Lojban so apologies in advance if that's the case!

The correct answer contains the event/state of donating, but the original English text is asking for a translation of "a donation" (like a gift) which would be `lo se dunda` rather than `lo nu dunda`.

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=11][exerciseId=1718]
- Exercise payload: {"sentences":[{"text":"Do you like donations motivated by happiness?","lojbanic":false}],"title":"Translate this sentence","type":"typing"}
- Attempted solution: {"text":"xu do nelci lo se dunda be mu'i lo nu gleki"}
- Attempted solution was classified as correct: no
- Validation payload: {"canonicalAnswer":"xu do nelci lo nu dunda mu'i lo nu gleki","correct":false}

**Comment by jqueiroz** [comment]
Thanks for reporting!

Interesting, I think in this case the issue originates from ambiguity in English :) When preparing the exercise, I was of "donation" as "event of donation" (as in "People are talking about the donation"). But indeed it can also be interpreted as "gift".

 To resolve the ambiguity, I changed the exercise prompt to "Do you like events of donations motivated by happiness?".
