### ISSUE TITLE
Add another ‘practise’ button to the bottom of each lesson page

### ISSUE THREAD

**Issue by uakci** [jqueiroz/lojban.io#14]

**Comment by jqueiroz** [comment]
Thank you for the feedback!

I will start working on this soon (unless someone else would like to take this).

**Comment by emorchy** [comment]
I like the idea of a practice button at the bottom. It saves time and it is a lot cleaner. Although I have very limited experience with haskell, I have created a pull request with a possible creation. I would appreciate any feedback and/or constructive criticism. Thank you.
