### ISSUE TITLE
Feedback regarding lesson: Sumtcita

### ISSUE THREAD

**Issue by Mecamute** [jqueiroz/lojban.io#142]
Please provide your feedback here...

In lesson 11 of the lojban course, one thing wasn't very clear for me, but I ended up grasping it after consulting The Incomplete Lojban Language.

9.5. Modal places: FIhO, FEhU (https://lojban.pw/cll/uncll-1.2.7/xhtml_section_chunks/section-selbri-modals.html)

"mi viska do fi'o kanla [fe'u] le zunle

It is important to remember that even though le zunle is placed following fi'o kanla, semantically **it belongs in the x1 place** of kanla. [...] Modal sumti [...] **may not be marked with FA** cmavo."

In my opinion, It should be explained in the lesson that only selbri can go into fi'o...fe'u. There's one example that was probably wrong, and it made me believe sumti could be placed inside fi'o...fe'u. This is the example:
**fi'o gasnu do {fe'u} mi vecnu lo skami**
I pasted the sentence into a parser, and the parser couldn't tell me the structure of the sentence. When I placed fe'u after gasnu it gave me a positive result.

It should also say in the lesson that what comes after fi'o SELBRI fe'u is the x1 of SELBRI.
Example: **fi'o[opening] mukti[selbri] {fe'u}[closing] ma[x1]** (Or something like that.)
Not saying this, will make people think they should place fa before the sumti.

It actually says that what comes after fi'o SELBRI fe'u is the x1 of SELBRI, but it does that in other words: **"This sumtcita then absorbs the next sumti."** and **"A sumtcita can only absorb one sumti, which is always the following one."** which isn't very clear for me (I don't know about other learners).

One more thing.
When I click in the contact button at the bottom of the page, nothing happens.

You guys are doing a great job. I had actually given up on lojban a long time ago, but your website sparkled a fire in me and motivated me to come back. I'm still a beginner, but hopefully one day I'll be able to help. Thank you!

### Context
For context, this feedback refers to the lesson "Sumtcita" in the course "Getting started with Lojban (alpha)".

**Comment by jqueiroz** [comment]
(Accidentally closed.)

**Comment by jqueiroz** [comment]
Thank you very much for the detailed feedback, it is really appreciated!

That example was indeed incorrect, it should have been "fi'o gasnu {fe'u} do mi vecnu lo skami". I fixed this example, and also made [some changes](https://github.com/jqueiroz/lojban.io/pull/143) to make the lesson clearer (they will be live in 10min or so). The previous version was indeed quite confusing. Please let me know if you think they helped, and also if there is anything that could be further clarified.

Thanks again!

**Comment by Mecamute** [comment]
I liked the new version. Thank you!
