### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=8][exerciseId=147]

### ISSUE THREAD

**Issue by shawnhouser** [jqueiroz/lojban.io#155]
# Description
The canonical answer does not require a secondary `do`, allowing the x1 of `ctuca` to be `zo'e` and translating to `You promised the event that someone would teach me` instead of the intended `You promised the event that *you* would teach me`. Talking to another person they say they have seen similar issues on other questions.

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=8][exerciseId=147]
- Exercise payload: {"shouldDisplayHint":false,"exercise":{"canonicalAnswer":"do nupre lo nu ctuca mi","sentences":[{"text":"You promised to teach me.","lojbanic":false}],"title":"Translate this sentence","type":"typing"}}
- Attempted solution: {"text":"do nupre lo nu do ctuca mi"}
- Attempted solution was classified as correct: yes
- Validation payload: {"canonicalAnswer":"do nupre lo nu ctuca mi","correct":true}

**Comment by jqueiroz** [comment]
Thank you for reporting!

In this case, this was by design. The canonical answer for this exercise is "do nupre lo nu ctuca mi kei ku", but the longer and more explicit "do nupre lo nu do ctuca mi kei ku" is also accepted.

**Comment by shawnhouser** [comment]
Yes I see now. Looking through the translation problems I can see both accepted versions there. I did not know there was a big list of those when I reported the issue, I'll make sure to look there and double check things before reporting them in the future.

Issue closed as intended behavior.
