### ISSUE TITLE
Feedback regarding lesson: Tenses 1

### ISSUE THREAD

**Issue by Interesting-name** [jqueiroz/lojban.io#156]
coi .ui
I've come across the sentence
> The same applies principle to the second example as well.

directly above the "Practice" heading, where apparently "applies" and "principle" got swapped.

### Context
For context, this feedback refers to the lesson "Tenses 1" in the course "Getting started with Lojban (alpha)".

**Comment by jqueiroz** [comment]
.ui coi lo cinryselcme no'u la cinri cmene

Fixed, thanks for reporting! :)
