### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=6][exerciseId=4083]

### ISSUE THREAD

**Issue by IFcoltransG** [jqueiroz/lojban.io#178]
# Description
The differences are that I put `cuska` after the x2 and I merged `se` and `du'u` into a word, both of which I thought were valid transformations. (I do admit I was trying to see what the parser can cope with.)

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=6][exerciseId=4083]
- Exercise payload: {"shouldDisplayHint":false,"exercise":{"canonicalAnswer":"mi cusku lo se du'u lo ciska ku pendo kei ku","sentences":[{"text":"I said that the writer would be a friend.","lojbanic":false}],"title":"Translate this sentence","type":"typing"}}
- Attempted solution: {"text":"mi lo sedu'u lo ciska ku pendo kei ku cuska"}
- Attempted solution was classified as correct: no
- Validation payload: {"canonicalAnswer":"mi cusku lo se du'u lo ciska ku pendo kei ku","correct":false}

**Comment by ChemistMikeLam** [comment]
I am afraid that `cuska` is not a defined gismu (although morphologically it is of a gismu form). There is `ciska` (which I assume you meant that), and there is `cusku`, but no `cuska`.
