### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=8][exerciseId=1831]

### ISSUE THREAD

**Issue by IFcoltransG** [jqueiroz/lojban.io#179]
# Description
Answer differs only in the space between `se` and `du'u`, which shouldn't matter for correctness.

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=8][exerciseId=1831]
- Exercise payload: {"shouldDisplayHint":false,"exercise":{"canonicalAnswer":"do cusku lo se du'u mi nelci lo gerku","sentences":[{"text":"You said that I like the dogs.","lojbanic":false}],"title":"Translate this sentence","type":"typing"}}
- Attempted solution: {"text":"do cuska lo sedu'u mi nelci lo gerku"}
- Attempted solution was classified as correct: no
- Validation payload: {"canonicalAnswer":"do cusku lo se du'u mi nelci lo gerku","correct":false}

**Comment by ChemistMikeLam** [comment]
Same misspelling as in #178.
