### ISSUE TITLE
Logging in with Google fails and instead gives me "Decoding of user info failed."

### ISSUE THREAD

**Issue by Joshument** [jqueiroz/lojban.io#190]
I am attempting to log into lojban.io on Windows 10 Home 20H2 on Firefox 95.0.2.

Steps to reproduce:
1. Visit lojban.io whilst signed out
2. Attempt to login using Google

Reloading the page also changes the message to "Acquisition of oauth2 token failed."

**Comment by ChemistMikeLam** [comment]
Possible duplicate of #116?

**Comment by Joshument** [comment]
Ah, thought I searched through it properly. My bad.
