### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=5][exerciseId=1570]

### ISSUE THREAD

**Issue by xoltar** [jqueiroz/lojban.io#79]
# Description
If possible, please provide a brief description of what is wrong with this exercise.

Description requests "you," but answer uses "mi" instead of "do"

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=5][exerciseId=1570]
- Exercise payload: {"sentences":[{"text":"Did you teach the cat?","lojbanic":false}],"title":"Translate this sentence","type":"typing"}
- Attempted solution: {"text":"xu do ctuca lo mlatu ku"}
- Attempted solution was classified as correct: no
- Validation payload: {"canonicalAnswer":"xu mi ctuca lo mlatu ku","correct":false}

**Comment by jqueiroz** [comment]
Fixed, thanks for reporting!
