### ISSUE TITLE
Incorrect exercise: [deckId=eng_contextualized-brivla][exerciseId=3046]

### ISSUE THREAD

**Issue by Ushiofan4life** [jqueiroz/lojban.io#85]
# Description
The obvious answer is correct, so this isn't a big problem since the exercise is still functional, but doesn't "do pu zdani ma" mean "who were you a house for?"
I think "Which house did you live in?" would be "ma pu zdani do", but I'm kind of new to this Lojban thing so I might be wrong.

# Diagnostics information (do not remove)
- Exercise identifier: [deckId=eng_contextualized-brivla][exerciseId=3046]
- Exercise payload: {"sentences":[{"text":"Which house did you live in?","lojbanic":false},{"text":"do pu ____ ma","lojbanic":true}],"title":"Complete the translation","type":"typing"}
- Attempted solution: {"text":"zdani"}
- Attempted solution was classified as correct: yes
- Validation payload: {"canonicalAnswer":"zdani","correct":true}

**Comment by jqueiroz** [comment]
Thank you for reporting!

You are correct. Indeed, "which house did you live in" could be translated as "ma pu zdani do" (literally, "what was a house for you?"). I fixed the exercise by changing the Lojban sentence to "do pu xabju ma noi zdani", just to make it a little closer to the English prompt, but your proposal is correct as well.
