### ISSUE TITLE
There is a typo in lecture 07 - terminator elision

### ISSUE THREAD

**Issue by oransimhony** [jqueiroz/lojban.io#9]
I think there is a typo in the following sentence (I put the typo in bold):
> ...we could write lo prenu {ku} cu tavla to indicate that there is still an implicit ku to terminate **lo mlatu**...

I think it should be:
> ...we could write lo prenu {ku} cu tavla to indicate that there is still an implicit ku to terminate **lo prenu**...

I will open a pull request to fix this.

**Comment by jqueiroz** [comment]
Thank you! Just approved the pull request.
