### ISSUE TITLE
Lesson 15 Minor Issue

### ISSUE THREAD

**Issue by yanqui-uxo** [jqueiroz/lojban.io#93]
Finally, there is a more concise way of writing some relative phrases. Instead of lo SELBRI pe SUMTI, one may instead write lo SUMTI SELBRI. For example, lo gerku pe mi becomes lo mi gerku. Similarly lo lo prenu ku gerku becomes lo gerku pe lo prenu, meaning "the dog of the person".

The second example seems to be reversed - shouldn't "lo gerku pe lo prenu" become "lo lo prenu ku gerku"?

Also - "possesive" and "possesions" should be spelled "possessive" and "possessions".

**Comment by jqueiroz** [comment]
Thank you @yanqui-uxo  for reporting! Physicist137 fixed it :)
