### ISSUE TITLE
Exercise could be ambiguous: [courseId=grammar-intro_eng][lessonNumber=3][exerciseId=4267]

### ISSUE THREAD

**Issue by vinivosh** [jqueiroz/lojban.io#94]
# Description
Not wrong in the slightest but the sentence _"People like me"_ could be understood as _"People that are similar to me"_ instead of _"People are fond of me"_, y'know? Of course one can deduce that the latter is what was meant, as _"prenu"_ has just one sumti place and, threfore, we wouldn't be able to construct the latter phrase using the tools we learned so far, but I still think that changing the sentence to _"People are fond of me"_ would be less ambiguous.

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=3][exerciseId=4267]
- Exercise payload: {"sentences":[{"text":"People like me.","lojbanic":false}],"title":"Translate this sentence","type":"typing"}
- Attempted solution: {"text":"lo prenu ku nelci mi"}
- Attempted solution was classified as correct: yes
- Validation payload: {"canonicalAnswer":"lo prenu ku nelci mi","correct":true}

**Comment by emorchy** [comment]
Thank you @vinivosh for opening this issue. I agree that there could be some confusion on the definition of "like". With that in mind, I do not believe the vocabulary word {simsa}, where "x1 looks/appears like x2" has been taught in the lesson yet. If the gismu was taught, then I would not hesitate to alter the exercise to limit confusion. However, {lo prenu simsa mi} and {lo prenu nelci mi} should not cause confusion if one has not been taught yet. Thanks again for submitting an issue, and we'd love to hear future feedback to help build lojban.io.

**Comment by vinivosh** [comment]
I see. Not having learned {simsa} yet kinda makes it impossible to mix these two definitions of "like" up, I guess.

**Comment by emorchy** [comment]
No worries. I am glad I could be of help. Feel free to create new issues if you have any more feedback regarding this project. Thank you!
